# Generated by Django 4.1.dev20211213070928 on 2022-05-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='image/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
