# Generated by Django 4.1.dev20211213070928 on 2022-05-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addproject', '0003_category_price_region_remove_partner_partner_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addproject.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='addproject',
            name='prices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addproject.price', verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='addproject',
            name='regions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addproject.region', verbose_name='Регион'),
        ),
    ]
